TesteMixFiscal/Models/Nota.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TesteMixFiscal.Models
{
    [Table("tbl_Nota")]
    public class Nota
    {
        
        [Key]
        public int NItemId { get; set; }

        public string Descricao { get; set; }

        public string CodItem { get; set; }

        public string DescCompl { get; set; }

        public long? Ean { get; set; }

        public int Qtd { get; set; }

        public decimal VlItem { get; set; }

        [NotMapped]
        public int Vinculo { get; set; }

        #region ForignKey

        [ForeignKey("Tipo")]
        public int TipoId { get; set; }

        public virtual Tipo Tipo { get; set; }

        #endregion
    }
}

TesteMixFiscal/Models/Tipo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TesteMixFiscal.Models
{
    [Table("tbl_Tipo")]
    public class Tipo
    {
        [Key]
        public int TipoId { get; set; }

        public string Nome { get; set; }

        
    }

}

TesteMixFiscal/Controllers/NotaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TesteMixFiscal.Context;
using TesteMixFiscal.Models;

namespace TesteMixFiscal.Controllers
{
    public class NotaController : Controller
    {
        private MixFiscalContext db = new MixFiscalContext();

        // GET: Nota
        public ActionResult Index()
        {
            var nota = db.Nota.Include(n => n.Tipo);
            return View(nota.ToList());
        }

        //[HttpPost]
        public ActionResult Pesquisa(string busca = null, int tipo = 0, List<Nota> oNota = null)
        {
            if (busca != null && tipo == 1)
            {
                return View(db.Nota.Include(n => n.Tipo).Where(x => x.TipoId == tipo));
            }
            else if (busca != null && tipo == 2)
            {
                return View(db.Nota.Include(n => n.Tipo).Where(x => x.TipoId == tipo));
            }
            else if (busca != null && tipo == 3)
            {
                return View(db.Nota.Include(n => n.Tipo).Where(x => x.Descricao.ToUpper().Contains(busca.ToUpper())).ToList());
            }

            var nota = oNota != null ? oNota : db.Nota.Include(n => n.Tipo).ToList();
            return View(nota.ToList());
        }

        public ActionResult Organizar(string nota)
        {
            int indexNfe = 0;
            int indexSped = 0;

            var oRegistroOrganizado = new List<Nota>();
            var registro = db.Nota.Include(x => x.Tipo).Where(x => x.Descricao == nota).ToList();

            var oNfe = registro.Where(x => x.TipoId == 1).ToList();
            var oSped = registro.Where(x => x.TipoId == 2).ToList();

            foreach (var nfe in oNfe)
            {
                indexSped = 0;
                indexNfe++;
                foreach (var sped in oSped)
                {
                    indexSped++;
                    if (nfe.CodItem == sped.CodItem)
                    {
                        nfe.DescCompl = sped.DescCompl;
                        nfe.Ean = sped.Ean;
                        nfe.Qtd = sped.Qtd;
                        nfe.VlItem = sped.VlItem;
                        nfe.Vinculo = indexSped;
                    }
                    if (nfe.DescCompl == sped.DescCompl)
                    {
                        nfe.CodItem = sped.CodItem;
                        nfe.Ean = sped.Ean;
                        nfe.Qtd = sped.Qtd;
                        nfe.VlItem = sped.VlItem;
                        nfe.Vinculo = indexSped;
                    }
                    else if (nfe.Ean == sped.Ean)
                    {
                        nfe.CodItem = sped.CodItem;
                        nfe.DescCompl = sped.DescCompl;
                        nfe.Qtd = sped.Qtd;
                        nfe.VlItem = sped.VlItem;
                        nfe.Vinculo = indexSped;
                    }
                    else if (nfe.Qtd == sped.Qtd && nfe.VlItem == sped.VlItem)
                    {
                        OrganizarPorDescricao(nfe, sped, indexSped);
                    }                    
                }
            }

            oRegistroOrganizado.AddRange(oNfe);
            oRegistroOrganizado.AddRange(oSped);

            return View(oRegistroOrganizado);
        }
        public void OrganizarPorDescricao(Nota nfe, Nota sped, int indexSped)
        {
            var descricaoSplit = nfe.DescCompl.Split(' ');

            foreach (var item1 in descricaoSplit.ToList())
            {
                foreach (var item2 in descricaoSplit.ToList())
                {
                    if (sped.DescCompl.Contains(item1) && sped.DescCompl.Contains(item2))
                    {
                        nfe.CodItem = sped.CodItem;
                        nfe.DescCompl = sped.DescCompl;
                        nfe.Ean = sped.Ean;
                        nfe.Qtd = sped.Qtd;
                        nfe.VlItem = sped.VlItem;
                        nfe.Vinculo = indexSped;
                    }
                }
            }
        }

        // GET: Nota/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nota nota = db.Nota.Find(id);
            if (nota == null)
            {
                return HttpNotFound();
            }
            return View(nota);
        }

        // GET: Nota/Create
        public ActionResult Create()
        {
            ViewBag.TipoId = new SelectList(db.Tipo, "TipoId", "Nome");
            return View();
        }

        // POST: Nota/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "NItemId,Descricao,CodItem,DescCompl,Ean,Qtd,VlItem,TipoId")] Nota nota)
        {
            if (ModelState.IsValid)
            {
                db.Nota.Add(nota);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TipoId = new SelectList(db.Tipo, "TipoId", "Nome", nota.TipoId);
            return View(nota);
        }

        // GET: Nota/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nota nota = db.Nota.Find(id);
            if (nota == null)
            {
                return HttpNotFound();
            }
            ViewBag.TipoId = new SelectList(db.Tipo, "TipoId", "Nome", nota.TipoId);
            return View(nota);
        }

        // POST: Nota/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "NItemId,Descricao,CodItem,DescCompl,Ean,Qtd,VlItem,TipoId")] Nota nota)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nota).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TipoId = new SelectList(db.Tipo, "TipoId", "Nome", nota.TipoId);
            return View(nota);
        }

        // GET: Nota/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nota nota = db.Nota.Find(id);
            if (nota == null)
            {
                return HttpNotFound();
            }
            return View(nota);
        }

        // POST: Nota/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Nota nota = db.Nota.Find(id);
            db.Nota.Remove(nota);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }

}

TesteMixFiscal/Views/Nota/Create.cshtml
@model TesteMixFiscal.Models.Nota

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Nota</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CodItem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CodItem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CodItem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescCompl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DescCompl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescCompl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ean, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ean, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ean, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Qtd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Qtd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Qtd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VlItem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VlItem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VlItem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoId, "TipoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TipoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TesteMixFiscal/Views/Nota/Delete.cshtml
@model TesteMixFiscal.Models.Nota

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Nota</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Tipo.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CodItem)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CodItem)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DescCompl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DescCompl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ean)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ean)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Qtd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Qtd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VlItem)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VlItem)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TesteMixFiscal/Views/Nota/Details.cshtml
@model TesteMixFiscal.Models.Nota

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Nota</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Tipo.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CodItem)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CodItem)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DescCompl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DescCompl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ean)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ean)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Qtd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Qtd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VlItem)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VlItem)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.NItemId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TesteMixFiscal/Views/Nota/Edit.cshtml
@model TesteMixFiscal.Models.Nota

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Nota</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.NItemId)

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CodItem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CodItem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CodItem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescCompl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DescCompl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DescCompl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ean, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ean, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ean, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Qtd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Qtd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Qtd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VlItem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VlItem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VlItem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoId, "TipoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TipoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TesteMixFiscal/Views/Nota/Index.cshtml
@model IEnumerable<TesteMixFiscal.Models.Nota>

@{
    ViewBag.Title = "Index";
}

<h2>Registro(s)</h2>


@using (Html.BeginForm("Pesquisa", "Nota", FormMethod.Get, new { @class = "form-inline" }))
{
    <div class="row">
        <div class="col-md-12" style="background-color:#e8e8e8; padding:10px; margin-bottom: 20px;">

            <input type="text" placeholder="Busca" name="busca" class="form-control" />
            <input type="submit" class="btn btn-default" value="buscar" />
            <br />

            <input type="radio" id="nfe" name="tipo" value="1" />
            <label for="nfe">Por NF-e</label>

            <br />

            <input type="radio" id="sped" name="tipo" value="2" />
            <label for="sped">Por SPED</label>
            <br />

            <input type="radio" id="Descricao" name="tipo" value="3" />
            <label for="Descricao">Por Descrição</label>
            <br />
        </div>
    </div>
}
<p>
    @Html.ActionLink("Create New", "Create")
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Tipo.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CodItem)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DescCompl)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ean)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Qtd)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VlItem)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Tipo.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descricao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CodItem)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DescCompl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ean)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Qtd)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VlItem)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.NItemId }) |
                @Html.ActionLink("Details", "Details", new { id = item.NItemId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.NItemId })
            </td>
        </tr>
    }

</table>

TesteMixFiscal/Views/Nota/Pesquisa.cshtml
@model IEnumerable<TesteMixFiscal.Models.Nota>

@{
    ViewBag.Title = "Pesquisa";
}

<h2>Registro(s)</h2>

<br />
<div class="row" style="margin-bottom: 15px;">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-6">
                @Html.ActionLink("Retornar aos Registros", "Index")
            </div>
            <div class="col-md-6" style="text-align:right;">
                @using (Html.BeginForm("Organizar", "Nota", FormMethod.Get, new { @class = "form-inline" }))
                {
                    <input type="hidden" placeholder="Busca" name="nota" class="form-control" value="@Request.QueryString["busca"]" />

                    <input type="submit" class="btn btn-danger" value="Organizar" />
                }
            </div>
        </div>
    </div>
</div>

@*Tabela do tipo NF-e*@
<table class="table">
    <caption>Tabela do tipo NF-e</caption>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Tipo.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CodItem)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DescCompl)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ean)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Qtd)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VlItem)
        </th>
    </tr>

    @foreach (var item in Model.Where(x => x.TipoId == 1))
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Tipo.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descricao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CodItem)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DescCompl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ean)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Qtd)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VlItem)
            </td>
        </tr>
    }

</table>

<br />
<br />

@*Tabela do Tipo SPED*@
<table class="table">
    <caption>Tabela do tipo SPED</caption>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Tipo.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CodItem)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DescCompl)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ean)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Qtd)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VlItem)
        </th>
    </tr>

    @foreach (var item in Model.Where(x => x.TipoId == 2))
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Tipo.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descricao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CodItem)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DescCompl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ean)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Qtd)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VlItem)
            </td>
        </tr>
    }

</table>

TesteMixFiscal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("TESTE - MIX FISCAL", "Index", "Nota", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Registros", "Index", "Nota")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>